import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
// Review the full license text and update THIRD_PARTY_NOTICES.md when changing
// any emitted dependency. Dev dependencies absent from the output need no banner.
const reviewedLicenses = {
  "@getpaseo/plugin": { version: "0.8.0", file: "paseo-0.8.0.txt" },
  "@iarna/toml": { version: "2.2.5", file: "iarna-toml-2.2.5.txt", installed: "LICENSE" },
  zod: { version: "4.6.5", file: "zod-4.6.5.txt", installed: "LICENSE" },
};
const result = await build({
  absWorkingDir: root,
  entryPoints: [join(root, "server/launcher-main.ts")], bundle: true, platform: "node", target: "node22",
  format: "cjs", write: false, minify: true, metafile: true, legalComments: "eof", logLevel: "warning",
});
const included = new Map();
for (const output of Object.values(result.metafile.outputs)) {
  for (const [input, { bytesInOutput }] of Object.entries(output.inputs)) {
    if (!bytesInOutput) continue;
    const marker = "node_modules/", offset = input.lastIndexOf(marker);
    if (offset < 0) continue;
    const parts = input.slice(offset + marker.length).split("/");
    const name = parts.slice(0, parts[0].startsWith("@") ? 2 : 1).join("/");
    const directory = join(root, input.slice(0, offset + marker.length), name);
    const metadata = JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
    const license = reviewedLicenses[name];
    if (!license || metadata.version !== license.version) {
      throw new Error(`Review and add a license for bundled dependency ${name}@${metadata.version}.`);
    }
    if (included.has(name)) continue;
    const text = await readFile(join(root, "licenses", license.file), "utf8");
    if (license.installed && text !== await readFile(join(directory, license.installed), "utf8")) {
      throw new Error(`The reviewed license for ${name} does not match the installed package.`);
    }
    if (!text.trim() || text.includes("*/")) throw new Error(`Invalid bundled license text for ${name}.`);
    included.set(name, `${name}@${metadata.version}\n\n${text}`);
  }
}
const notices = [...included.keys()].sort().map(name => included.get(name)).join("\n\n---\n\n");
const banner = `#!/usr/bin/env node\n/*!\nThird-party notices for the Account Switcher standalone launcher.\nDependencies are bundled and minified by esbuild; their source code is otherwise unmodified.\n\n${notices}\n*/\n`;
const source = banner + result.outputFiles[0].text;
await writeFile(join(root, "server/launcher-artifact.ts"), `// Generated by npm run build. Do not edit. Self-contained native-provider launcher.\nexport const LAUNCHER_SOURCE = ${JSON.stringify(source)};\n`);
console.log(`Standalone launcher built (${Buffer.byteLength(source)} bytes; ${included.size} third-party licenses included).`);
